### PR TITLE
add jenkins pipeline support

### PR DESCRIPTION
**Pull request by sitzm**

### CODE REVIEW

**Comment by dtydeman** [comment]
Is there any way this can be merged in? looks like a great addition of important functionality

**Comment by empireij** [comment]
How is it looking?

**Comment by Amila17** [comment]
Hi Guys,

Can we get this merged if everything is looking good? We would like to utilise this plugin for our pipeline approach.

Thanks!

**Comment by Aft3rm4thx** [comment]
@vipinsthename is there a possibility of getting this merged in?  It looks like it'd help a decent amount of folks.

**Comment by terrafying** [comment]
I think we should transfer ownership of this project to somebody who will approve PRs

**Comment by michaelsbroughton** [comment]
@vipinsthename - Can you please review and merge this pull request then publish it to Jenkins plugins?

**Comment by mominkhan** [comment]
> I think we should transfer ownership of this project to somebody who will approve PRs

An issue has been raised separately. 
[https://github.com/vipinsthename/environment-dashboard/issues/147](url)

If @vipinsthename can provide his consent for transfer of ownership of the plugin then someone in the community can adopt it.

**Pull request merged**
